import React from 'react'
import { useParams } from 'react-router-dom';


export default function PressRelease() {
    const { pressRelease } = useParams();
    function test(){
        console.log(pressRelease);
    }
    const heading = 'Global Cassava Starch Market To Grow At A CAGR Of 5.5% By 2030'
    return (
        <>
            <div onClick={test} className="max-w-6xl px-4 mx-auto sm:px-6">
            <div className='py-4'> Congruence / Report / Information & Communication Technology / Workforce Analytics Market</div>
                <div className="py-2 text-center md:pt-2 md:text-left">
                    <div className="pb-12 mx-auto max-w-8xl md:pb-10">
                        <div className='md:flex'>
                            <div className="w-full">
                                <div className='relative p-4 border rounded-md'>
                                    <div className='absolute top-[-10px] right-[20px] py-1 px-4 bg-primary text-white rounded-sm'>
                                        13 Oct 2023
                                    </div>

                                    <div className="mb-2 text-xl font-semibold">{heading}</div>
                                    <div className='flex flex-col gap-2 py-2'>
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia perspiciatis nesciunt nam, corrupti, tempora incidunt illo dolores consectetur impedit temporibus aspernatur dolorum sapiente optio facilis iste odit ea maxime non. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum, molestiae debitis! Nulla quo rem beatae expedita eligendi distinctio earum minus quam ex excepturi consequatur consequuntur, voluptate quod! Cumque, esse id. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus, quas dicta ratione, ducimus iure animi distinctio repellat, accusamus dignissimos debitis sapiente rerum nulla ipsa sed commodi modi sunt deleniti quis.
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia perspiciatis nesciunt nam, corrupti, tempora incidunt illo dolores consectetur impedit temporibus aspernatur dolorum sapiente optio facilis iste odit ea maxime non. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum, molestiae debitis! Nulla quo rem beatae expedita eligendi distinctio earum minus quam ex excepturi consequatur consequuntur, voluptate quod! Cumque, esse id. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus, quas dicta ratione, ducimus iure animi distinctio repellat, accusamus dignissimos debitis sapiente rerum nulla ipsa sed commodi modi sunt deleniti quis.
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia perspiciatis nesciunt nam, corrupti, tempora incidunt illo dolores consectetur impedit temporibus aspernatur dolorum sapiente optio facilis iste odit ea maxime non. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum, molestiae debitis! Nulla quo rem beatae expedita eligendi distinctio earum minus quam ex excepturi consequatur consequuntur, voluptate quod! Cumque, esse id. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus, quas dicta ratione, ducimus iure animi distinctio repellat, accusamus dignissimos debitis sapiente rerum nulla ipsa sed commodi modi sunt deleniti quis.
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia perspiciatis nesciunt nam, corrupti, tempora incidunt illo dolores consectetur impedit temporibus aspernatur dolorum sapiente optio facilis iste odit ea maxime non. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum, molestiae debitis! Nulla quo rem beatae expedita eligendi distinctio earum minus quam ex excepturi consequatur consequuntur, voluptate quod! Cumque, esse id. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus, quas dicta ratione, ducimus iure animi distinctio repellat, accusamus dignissimos debitis sapiente rerum nulla ipsa sed commodi modi sunt deleniti quis.
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia perspiciatis nesciunt nam, corrupti, tempora incidunt illo dolores consectetur impedit temporibus aspernatur dolorum sapiente optio facilis iste odit ea maxime non. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum, molestiae debitis! Nulla quo rem beatae expedita eligendi distinctio earum minus quam ex excepturi consequatur consequuntur, voluptate quod! Cumque, esse id. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus, quas dicta ratione, ducimus iure animi distinctio repellat, accusamus dignissimos debitis sapiente rerum nulla ipsa sed commodi modi sunt deleniti quis.
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia perspiciatis nesciunt nam, corrupti, tempora incidunt illo dolores consectetur impedit temporibus aspernatur dolorum sapiente optio facilis iste odit ea maxime non. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum, molestiae debitis! Nulla quo rem beatae expedita eligendi distinctio earum minus quam ex excepturi consequatur consequuntur, voluptate quod! Cumque, esse id. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus, quas dicta ratione, ducimus iure animi distinctio repellat, accusamus dignissimos debitis sapiente rerum nulla ipsa sed commodi modi sunt deleniti quis.
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia perspiciatis nesciunt nam, corrupti, tempora incidunt illo dolores consectetur impedit temporibus aspernatur dolorum sapiente optio facilis iste odit ea maxime non. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum, molestiae debitis! Nulla quo rem beatae expedita eligendi distinctio earum minus quam ex excepturi consequatur consequuntur, voluptate quod! Cumque, esse id. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus, quas dicta ratione, ducimus iure animi distinctio repellat, accusamus dignissimos debitis sapiente rerum nulla ipsa sed commodi modi sunt deleniti quis.
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia perspiciatis nesciunt nam, corrupti, tempora incidunt illo dolores consectetur impedit temporibus aspernatur dolorum sapiente optio facilis iste odit ea maxime non. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum, molestiae debitis! Nulla quo rem beatae expedita eligendi distinctio earum minus quam ex excepturi consequatur consequuntur, voluptate quod! Cumque, esse id. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus, quas dicta ratione, ducimus iure animi distinctio repellat, accusamus dignissimos debitis sapiente rerum nulla ipsa sed commodi modi sunt deleniti quis.
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia perspiciatis nesciunt nam, corrupti, tempora incidunt illo dolores consectetur impedit temporibus aspernatur dolorum sapiente optio facilis iste odit ea maxime non. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum, molestiae debitis! Nulla quo rem beatae expedita eligendi distinctio earum minus quam ex excepturi consequatur consequuntur, voluptate quod! Cumque, esse id. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus, quas dicta ratione, ducimus iure animi distinctio repellat, accusamus dignissimos debitis sapiente rerum nulla ipsa sed commodi modi sunt deleniti quis.
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia perspiciatis nesciunt nam, corrupti, tempora incidunt illo dolores consectetur impedit temporibus aspernatur dolorum sapiente optio facilis iste odit ea maxime non. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum, molestiae debitis! Nulla quo rem beatae expedita eligendi distinctio earum minus quam ex excepturi consequatur consequuntur, voluptate quod! Cumque, esse id. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus, quas dicta ratione, ducimus iure animi distinctio repellat, accusamus dignissimos debitis sapiente rerum nulla ipsa sed commodi modi sunt deleniti quis.
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia perspiciatis nesciunt nam, corrupti, tempora incidunt illo dolores consectetur impedit temporibus aspernatur dolorum sapiente optio facilis iste odit ea maxime non. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum, molestiae debitis! Nulla quo rem beatae expedita eligendi distinctio earum minus quam ex excepturi consequatur consequuntur, voluptate quod! Cumque, esse id. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus, quas dicta ratione, ducimus iure animi distinctio repellat, accusamus dignissimos debitis sapiente rerum nulla ipsa sed commodi modi sunt deleniti quis.
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia perspiciatis nesciunt nam, corrupti, tempora incidunt illo dolores consectetur impedit temporibus aspernatur dolorum sapiente optio facilis iste odit ea maxime non. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum, molestiae debitis! Nulla quo rem beatae expedita eligendi distinctio earum minus quam ex excepturi consequatur consequuntur, voluptate quod! Cumque, esse id. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus, quas dicta ratione, ducimus iure animi distinctio repellat, accusamus dignissimos debitis sapiente rerum nulla ipsa sed commodi modi sunt deleniti quis.
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia perspiciatis nesciunt nam, corrupti, tempora incidunt illo dolores consectetur impedit temporibus aspernatur dolorum sapiente optio facilis iste odit ea maxime non. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum, molestiae debitis! Nulla quo rem beatae expedita eligendi distinctio earum minus quam ex excepturi consequatur consequuntur, voluptate quod! Cumque, esse id. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus, quas dicta ratione, ducimus iure animi distinctio repellat, accusamus dignissimos debitis sapiente rerum nulla ipsa sed commodi modi sunt deleniti quis.
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia perspiciatis nesciunt nam, corrupti, tempora incidunt illo dolores consectetur impedit temporibus aspernatur dolorum sapiente optio facilis iste odit ea maxime non. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum, molestiae debitis! Nulla quo rem beatae expedita eligendi distinctio earum minus quam ex excepturi consequatur consequuntur, voluptate quod! Cumque, esse id. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus, quas dicta ratione, ducimus iure animi distinctio repellat, accusamus dignissimos debitis sapiente rerum nulla ipsa sed commodi modi sunt deleniti quis.
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia perspiciatis nesciunt nam, corrupti, tempora incidunt illo dolores consectetur impedit temporibus aspernatur dolorum sapiente optio facilis iste odit ea maxime non. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum, molestiae debitis! Nulla quo rem beatae expedita eligendi distinctio earum minus quam ex excepturi consequatur consequuntur, voluptate quod! Cumque, esse id. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus, quas dicta ratione, ducimus iure animi distinctio repellat, accusamus dignissimos debitis sapiente rerum nulla ipsa sed commodi modi sunt deleniti quis.
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia perspiciatis nesciunt nam, corrupti, tempora incidunt illo dolores consectetur impedit temporibus aspernatur dolorum sapiente optio facilis iste odit ea maxime non. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum, molestiae debitis! Nulla quo rem beatae expedita eligendi distinctio earum minus quam ex excepturi consequatur consequuntur, voluptate quod! Cumque, esse id. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus, quas dicta ratione, ducimus iure animi distinctio repellat, accusamus dignissimos debitis sapiente rerum nulla ipsa sed commodi modi sunt deleniti quis.
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia perspiciatis nesciunt nam, corrupti, tempora incidunt illo dolores consectetur impedit temporibus aspernatur dolorum sapiente optio facilis iste odit ea maxime non. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum, molestiae debitis! Nulla quo rem beatae expedita eligendi distinctio earum minus quam ex excepturi consequatur consequuntur, voluptate quod! Cumque, esse id. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Temporibus, quas dicta ratione, ducimus iure animi distinctio repellat, accusamus dignissimos debitis sapiente rerum nulla ipsa sed commodi modi sunt deleniti quis.
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}
